[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "guide"
version = "0.1.0"

[project.scripts]
build-oulad-dataset = "src.oulad.build_dataset:main"
