name: guide-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - jupyterlab
  - notebook
  - pytest
  - black
  - isort
  - ruff
  - pre-commit
  # GPU-enabled PyTorch from conda
  - pytorch>=2.0.0
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - pip:
      # Core ML and data science
      - fairlearn>=0.12.0
      - aif360>=0.6.0
      - statsmodels>=0.14.0
      - tqdm>=4.65.0
      # Explainability
      - shap>=0.48.0
      - lime>=0.2.0
      - dice-ml>=0.11.0
      - dowhy>=0.11.0
      # Web interface
      - streamlit>=1.28.0
      - altair>=5.0.0
      # Additional ML libraries
      - torch-geometric>=2.3.0
      - hmmlearn>=0.3.0
      # CLI and configuration
      - typer>=0.9.0
      - pydantic>=2.0.0
      - hydra-core>=1.3.0
      # Process mining
      - pm4py>=2.7.0
      # Testing and quality
      - pytest-cov>=4.1.0
      - nbstripout>=0.6.0
      # Additional dependencies from requirements.txt
      - requests
variables:
  - PYTHONHASHSEED=0
  - CUDA_VISIBLE_DEVICES=0