name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONHASHSEED: 0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest black
      - name: Style check
        run: black --check .
      - name: Run tests
        run: pytest
      - name: Dashboard image verification
        run: pytest tests/test_dashboard_images.py
