name: Experiment Report

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure reporter deps even if not listed
          pip install --upgrade pandas numpy scipy seaborn matplotlib

      - name: Generate experiment report
        run: |
          python scripts/aggregate_results.py \
            --input-dir results \
            --out docs/experiment_report.md \
            --plots-dir docs/figures \
            --alpha 0.05

      - name: Attach report to Job Summary
        if: always()
        run: |
          echo "## Experiment Report" >> $GITHUB_STEP_SUMMARY
          if [ -f docs/experiment_report.md ]; then
            cat docs/experiment_report.md >> $GITHUB_STEP_SUMMARY
          else
            echo "_No report generated (no results found?)._" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload report artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: experiment-report
          path: |
            docs/experiment_report.md
            docs/figures/**
          if-no-files-found: warn